version: '3.9'

services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx-container
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nest-aws-container
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    restart: on-failure
    # command: sh -c "pnpm run start:integ"
